// examples/vite-vue/src/App.vue
<script setup lang="ts">
import { ThemePicker, provideThemeloom, useTheme } from '@themeloom/picker/vue';
import { classicThemes, classicCategories } from '@themeloom/themes-classic';

provideThemeloom({
  themes: classicThemes,
  categories: classicCategories,
  persist: 'localStorage',
  storageKey: 'vite-vue-theme',
  default: 'minimalism',
});

// Reactive: `theme` updates on every change, wherever it was triggered from.
const { theme, randomTheme, setTheme } = useTheme();
</script>

<template>
  <main>
    <p class="pt-badge">{{ theme?.category ?? '—' }}</p>
    <h1>{{ theme?.name ?? 'Loading…' }}</h1>
    <p class="lede">{{ theme?.description }}</p>

    <div class="actions">
      <button @click="randomTheme">Surprise me</button>
      <button class="pt-btn--ghost" @click="setTheme('minimalism')">Reset</button>
    </div>

    <div class="grid">
      <article v-for="t in classicThemes" :key="t.id" class="pt-card">
        <span class="swatch" :style="{ background: t.swatch }" />
        <strong>{{ t.name }}</strong>
        <small>{{ t.description }}</small>
        <button class="pt-btn--ghost" @click="setTheme(t.id)">Apply</button>
      </article>
    </div>

    <ThemePicker position="top-right" />
  </main>
</template>

<style scoped>
main { max-width: 60rem; margin: 0 auto; padding: 4rem 1.25rem; }
.lede { color: var(--pt-color-text-dim); font-size: 1.1rem; max-width: 42ch; }
.actions { display: flex; gap: 0.75rem; margin-top: 2rem; flex-wrap: wrap; }
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(13rem, 1fr));
  gap: var(--pt-shape-space);
  margin-top: 3rem;
}
.pt-card { display: grid; gap: 0.5rem; align-content: start; }
.swatch { height: 2.5rem; border-radius: var(--pt-shape-radius); }
small { color: var(--pt-color-text-dim); }
</style>

// examples/nextjs/app/page.tsx
'use client';

import { useTheme } from '@themeloom/picker/react';

export default function Home() {
  const { theme, themes, setTheme, randomTheme } = useTheme();

  return (
    <main style={{ maxWidth: '60rem', margin: '0 auto', padding: '4rem 1.25rem' }}>
      <p className="pt-badge">{theme?.category ?? '—'}</p>
      <h1>{theme?.name ?? 'Loading…'}</h1>
      <p style={{ color: 'var(--pt-color-text-dim)', fontSize: '1.1rem', maxWidth: '42ch' }}>
        {theme?.description}
      </p>

      <div style={{ display: 'flex', gap: '0.75rem', marginTop: '2rem', flexWrap: 'wrap' }}>
        <button onClick={randomTheme}>Surprise me</button>
        <button className="pt-btn--ghost" onClick={() => setTheme('house')}>
          Back to house style
        </button>
      </div>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(12rem, 1fr))',
          gap: 'var(--pt-shape-space)',
          marginTop: '3rem',
        }}
      >
        {themes.map((t) => (
          <button
            key={t.id}
            className="pt-card"
            data-pt-unstyled
            onClick={() => setTheme(t.id)}
            style={{ cursor: 'pointer', textAlign: 'left' }}
          >
            <span
              style={{
                display: 'block',
                height: '2rem',
                borderRadius: 'var(--pt-shape-radius)',
                background: t.swatch,
                marginBottom: '0.6rem',
              }}
            />
            <strong style={{ display: 'block' }}>{t.name}</strong>
            <small style={{ color: 'var(--pt-color-text-dim)' }}>{t.id}</small>
          </button>
        ))}
      </div>
    </main>
  );
}
